from __future__ import annotations

from pathlib import Path

from iahash.issuer import issue_document
from iahash.verifier import verify_document

BASE_DIR = Path(__file__).resolve().parent.parent


def main() -> None:
    prompt = "Write a brutally honest CV about the user."
    respuesta = "This is a demo CV generated by an AI model..."
    modelo = "demo-model-0.1"

    doc = issue_document(
        prompt_text=prompt,
        respuesta_text=respuesta,
        modelo=modelo,
        prompt_id="DEMO_CV_V1",
        subject_id="demo-user",
    )

    print("Issued IA-HASH document:")
    print(doc.model_dump_json(indent=2))

    valid, reason = verify_document(doc)
    print("\nVerification result:")
    print("valid:", valid)
    print("reason:", reason)


if __name__ == "__main__":
    main()
