from pydantic import BaseModel


class IAHashDocument(BaseModel):
    version: str = "IA-HASH-1"
    prompt_id: str | None = None
    prompt_maestro: str
    respuesta: str
    modelo: str
    timestamp: str
    subject_id: str | None = None

    h_prompt: str
    h_respuesta: str
    h_total: str
    firma_total: str

    issuer_id: str = "ia-hash.com"
    issuer_pk_url: str | None = None


class IssueFromTextRequest(BaseModel):
    """
    Input payload for issuing an IA-HASH document directly
    from raw prompt + raw LLM response via the web UI.
    """
    prompt_maestro: str          # Raw prompt used with the LLM
    respuesta: str               # Raw response generated by the LLM
    modelo: str | None = None    # Optional model name (e.g. 'gpt-5.1-thinking')
    prompt_id: str | None = None # Optional logical id for the prompt
    subject_id: str | None = None  # Optional user/subject identifier (e.g. 'manu_cabral')
